import { Dynasty } from './types';

export const DYNASTIES: Dynasty[] = [
  {
    id: 'xia',
    name: 'Xia Dynasty',
    chineseName: '夏朝',
    period: '约公元前 2070 年 – 约公元前 1600 年',
    description: '传统史学中记载的第一个世袭制朝代，标志着从新石器时代向青铜时代的过渡。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Bronze_Jue_%28Wine_Vessel%29%2C_Xia_Dynasty.jpg/800px-Bronze_Jue_%28Wine_Vessel%29%2C_Xia_Dynasty.jpg', 
  },
  {
    id: 'shang',
    name: 'Shang Dynasty',
    chineseName: '商朝',
    period: '约公元前 1600 年 – 约公元前 1046 年',
    description: '以精湛的青铜铸造、甲骨文以及中国最早的确切文字记录而闻名。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Houmuwu_Ding_db.jpg/800px-Houmuwu_Ding_db.jpg', 
  },
  {
    id: 'zhou',
    name: 'Zhou Dynasty',
    chineseName: '周朝',
    period: '约公元前 1046 年 – 公元前 256 年',
    description: '历史上延续时间最长的朝代，以“天命观”以及儒家、道家思想的兴起而著称。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Western_Zhou_Bronze_Gui.jpg/800px-Western_Zhou_Bronze_Gui.jpg', 
  },
  {
    id: 'qin',
    name: 'Qin Dynasty',
    chineseName: '秦朝',
    period: '公元前 221 年 – 公元前 206 年',
    description: '第一个统一的封建王朝，统一度量衡、文字，并修筑了长城。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Terracotta_Army_soldiers.jpg/800px-Terracotta_Army_soldiers.jpg', 
  },
  {
    id: 'han',
    name: 'Han Dynasty',
    chineseName: '汉朝',
    period: '公元前 202 年 – 公元 220 年',
    description: '中国历史上的黄金时代，见证了丝绸之路的开辟和造纸术的发明。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Gilt_Bronze_Human-Shaped_Lamp.JPG/800px-Gilt_Bronze_Human-Shaped_Lamp.JPG', 
  },
  {
    id: 'three_kingdoms',
    name: 'Three Kingdoms',
    chineseName: '三国',
    period: '公元 220 年 – 280 年',
    description: '魏、蜀、吴三国鼎立的局面，因《三国演义》等文学作品和戏曲而广为流传。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Guan_Yu_captured_Yu_Jin.jpg/800px-Guan_Yu_captured_Yu_Jin.jpg', 
  },
  {
    id: 'tang',
    name: 'Tang Dynasty',
    chineseName: '唐朝',
    period: '公元 618 年 – 907 年',
    description: '中华文明的巅峰，以开放包容的文化、辉煌的诗歌（李白、杜甫）和疆域扩张著称。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Spring_Outing_of_the_Tang_Court_by_Zhang_Xuan.jpg/1280px-Spring_Outing_of_the_Tang_Court_by_Zhang_Xuan.jpg', 
  },
  {
    id: 'song',
    name: 'Song Dynasty',
    chineseName: '宋朝',
    period: '公元 960 年 – 1279 年',
    description: '经济与文化高度发达的时代，最早使用了纸币和火药，宋词艺术达到顶峰。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Along_the_River_During_the_Qingming_Festival_%28Qingming_Shanghe_Tu%29_by_Zhang_Zeduan_%281085%E2%80%931145%29_crop.jpg/1280px-Along_the_River_During_the_Qingming_Festival_%28Qingming_Shanghe_Tu%29_by_Zhang_Zeduan_%281085%E2%80%931145%29_crop.jpg', 
  },
  {
    id: 'yuan',
    name: 'Yuan Dynasty',
    chineseName: '元朝',
    period: '公元 1271 年 – 1368 年',
    description: '由蒙古族忽必烈建立，是中国历史上第一个由少数民族统一全国的朝代。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Yuan_Dynasty_blue_and_white_porcelain_jar_with_fish_and_aquatic_plants.jpg/800px-Yuan_Dynasty_blue_and_white_porcelain_jar_with_fish_and_aquatic_plants.jpg', 
  },
  {
    id: 'ming',
    name: 'Ming Dynasty',
    chineseName: '明朝',
    period: '公元 1368 年 – 1644 年',
    description: '以修建紫禁城、郑和下西洋以及精美的瓷器闻名于世，是汉族建立的最后一个封建王朝。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/The_Forbidden_City_viewed_from_Jingshan_Hill.jpg/1280px-The_Forbidden_City_viewed_from_Jingshan_Hill.jpg', 
  },
  {
    id: 'qing',
    name: 'Qing Dynasty',
    chineseName: '清朝',
    period: '公元 1644 年 – 1912 年',
    description: '中国最后一个封建王朝，由满族统治，奠定了现代中国的版图基础。',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/The_Cixi_Imperial_Dowager_Empress_of_China_by_Hubert_Vos.jpg/800px-The_Cixi_Imperial_Dowager_Empress_of_China_by_Hubert_Vos.jpg', 
  }
];